pluginName = EVitest
pluginProvider = RoiSoleil
launchConfigurationType.name = Vitest
launchDelegate.name = Vitest
launchDelegate.description = Runs Vitest and shows its results in the Unit Test view.
tabGroup.run = Run the Vitest tests
tabGroup.debug = Debug the Vitest tests
shortcut.label = Vitest Test
shortcut.run = Runs the Vitest tests
shortcut.debug = Debugs the Vitest tests
codeMiningProvider.label = Run | Debug above the Vitest tests
preferencePage.name = EVitest
